import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { basename, dirname, relative, resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { parseRecipe } from '../src/parser/index.ts';
import { loadVocabulary } from '../src/vocabulary/node.ts';
import { auditConversion, qualityModel } from '../src/conversion-quality.ts';
import { recipeFiles } from './corpus.ts';
const vocabulary=await loadVocabulary('.');
const results: (ReturnType<typeof auditConversion> & { slug: string; title: string; source: { path: string; sha256: string; current: string; original: (import('../src/model/index.ts').OriginalSourcePayload | undefined)[] } })[]=[];
for(const file of await recipeFiles('examples/public-domain-recipes')){
 const source=await readFile(file,'utf8');const recipe=parseRecipe(source,{filename:file,vocabulary});
 const title=recipe.sections.flatMap(s=>s.children).find(n=>n.kind==='metadata'&&n.key==='name');
 results.push({slug:basename(dirname(file)),title:title?.kind==='metadata'?title.value:basename(dirname(file)),source:{path:relative('.',file).replaceAll('\\','/'),sha256:createHash('sha256').update(source).digest('hex'),current:source,original:recipe.sections.filter(s=>s.originalSource).map(s=>s.originalSource)},...auditConversion(recipe,vocabulary)});
}
results.sort((a,b)=>a.score-b.score||a.slug.localeCompare(b.slug));
const distribution=(values:number[])=>Object.fromEntries([[0,20],[20,40],[40,60],[60,80],[80,101]].map(([a,b])=>[`${a}-${b===101?100:b+' exclusive'}`,values.filter(v=>v>=a&&v<b).length]));
const aggregate=(key:'ingredients'|'equipment')=>{const total=results.reduce((n,r)=>n+r[key].total,0),referenced=results.reduce((n,r)=>n+r[key].referenced,0);return {total,referenced,percentage:100*referenced/total,distribution:distribution(results.flatMap(r=>r[key].percentage===null?[]:[r[key].percentage!])),notApplicable:results.filter(r=>r[key].percentage===null).length}};
const scores=results.map(r=>r.score);const summary={recipes:results.length,parserErrors:results.reduce((n,r)=>n+r.parser.errors,0),bands:Object.fromEntries(['strong','acceptable','partial','poor'].map(b=>[b,results.filter(r=>r.band===b).length])),mean:scores.reduce((a,b)=>a+b,0)/scores.length,median:(scores[Math.floor((scores.length-1)/2)]+scores[Math.floor(scores.length/2)])/2,scoreDistribution:distribution(scores),ingredients:aggregate('ingredients'),equipment:aggregate('equipment'),ruleCounts:Object.fromEntries(Object.keys(qualityModel.rules).map(k=>[k,results.reduce((n,r)=>n+(r.ruleCounts[k]??0),0)]))};
const out=resolve('work/conversion-quality');await mkdir(out,{recursive:true});
const caveats=['Quality warnings are not parser errors or semantic-fidelity verdicts. No source repair is performed.','Coverage counts declaration occurrences (including choice labels/alternatives); an indirect choice use does not prove each alternative was used. Ambiguous references remain uncovered.','Optional/garnish/serving declarations and implicit equipment can legitimately be uncovered. Empty declaration sets are N/A, not 100%; their score weight is redistributed.','CQ003 matches whole, unambiguous vocabulary names only for declared/resolved concepts, longest overlapping match first. It excludes process parameters, comments and Original source; this intentionally misses some leakage.','CQ004 counts physical instruction lines, not culinary actions. CQ005 can flag legitimate timing/qualifier detail. CQ006 measures syntax occupancy, so an overstuffed token can inflate density; CQ005 partially counterbalances it.','Empirical threshold review: a 12-word process cutoff flagged the single-action spaghetti-and-meatballs heat instruction (13 words). The baseline uses 16 words/100 characters instead. Longer legitimate qualifiers can still trigger CQ005. Process-name homographs such as brown, smoke and smooth can inflate verb evidence; this remains a candidate warning, not an action parse.','CQ007 is low confidence and has zero score weight. Coverage/leakage/density can correlate; each has a capped component weight.','Scores rank structural conversion only. No automatic accept/reject threshold for repairs or CI is established.'];
const report={schemaVersion:1,sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceDirty:!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),model:qualityModel,summary,caveats,results};
await writeFile(out+'/conversion-quality-audit.json',JSON.stringify(report,null,2)+'\n');
const table=(rs:typeof results)=>['| Recipe | Score / band | Ingredients | Equipment | Raw / long / process |','| --- | --- | --- | --- | --- |',...rs.map(r=>`| ${r.slug} | ${r.score} / ${r.band} | ${r.ingredients.referenced}/${r.ingredients.total} | ${r.equipment.referenced}/${r.equipment.total} | ${r.ruleCounts.CQ003} / ${r.ruleCounts.CQ004} / ${r.ruleCounts.CQ005} |`)].join('\n');
const md=['# Conversion-quality baseline','',`Audited ${results.length} promoted recipes. Parser errors: ${summary.parserErrors}. This is a structural quality heuristic, not parser validity.`, '', '## Model','```json',JSON.stringify(qualityModel,null,2),'```','','Score = 100 × weighted mean of applicable component ratios. Coverage is referenced/declared. Leakage = 1 − raw/(raw + unambiguous thing uses). Prose = 1 − flagged lines/all instruction lines. Processes = 1 − flagged/process tokens. Density = min(1, structural character fraction/0.5). Values contribute occupied characters without overlap; token count excludes values/operators. N/A weights are redistributed.','', '## Corpus summary','```json',JSON.stringify(summary,null,2),'```','', '## Strongest 20',table([...results].sort((a,b)=>b.score-a.score||a.slug.localeCompare(b.slug)).slice(0,20)),'','## Weakest 50',table(results.slice(0,50)),'','## Weakest recipe details',...results.slice(0,50).map(r=>`\n### ${r.slug}\n\nUnreferenced ingredients: ${r.ingredients.unreferenced.map(i=>i.raw).join('; ')||'none'}.\n\nUnreferenced equipment: ${r.equipment.unreferenced.map(i=>i.raw).join('; ')||'none'}. Structural coverage: ${r.metrics.structuralCharacterPercentage}%.\n\n${r.diagnostics.filter(d=>['CQ003','CQ004','CQ005'].includes(d.rule)).slice(0,3).map(d=>`- ${d.rule}, line ${d.span.line}: ${d.message} ${JSON.stringify(d.evidence)}`).join('\n')}`),'','## Unusual diagnostics',...['CQ003','CQ004','CQ005','CQ007'].map(k=>`${k}: `+[...results].sort((a,b)=>(b.ruleCounts[k]??0)-(a.ruleCounts[k]??0)||a.slug.localeCompare(b.slug)).slice(0,5).map(r=>`${r.slug} (${r.ruleCounts[k]})`).join(', ')),'','## Caveats',...caveats.map(c=>'- '+c),'','Full per-recipe diagnostics, exact UTF-16 spans, current source and preserved Original payloads: [JSON report](conversion-quality-audit.json).',''].join('\n');
await writeFile(out+'/CONVERSION-QUALITY-AUDIT.md',md);
console.log(JSON.stringify({output:out,...summary},null,2));
if(summary.parserErrors)process.exitCode=1;
